DROP TABLE IF EXISTS todos;
CREATE TABLE Todos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT (datetime(CURRENT_TIMESTAMP, 'localtime')),
  is_done BOOLEAN DEFAULT 0
)
